version: "3.3"
services:

  traefik:
    networks:
      traefik-proxy:
    image: "traefik:v3.0"
    container_name: "traefik"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.to-https.rule=hostregexp(`.+.m300.smartlearn.ch`)"

      - traefik.http.routers.to-https.entrypoints=web
      - traefik.http.routers.to-https.middlewares=to-https

      - traefik.http.routers.traefik.rule=Host(`traefik.m300.smartlearn.ch`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=${CERT_RESOLVER}

      - traefik.http.middlewares.to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PASSWORD_HASH}

    ports:
      - 80:80
      - 443:443

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./letsencrypt:/letsencrypt
      - ./traefik:/etc/traefik
      - /data/traefik-certs/cert.pem:/etc/traefik/certs/defaults/cert.pem
      - /data/traefik-certs/privkey.pem:/etc/traefik/certs/defaults/privkey.pem

networks:
  traefik-proxy:
    external:
      name: traefik-proxy
